# @no-redirect
GET http://localhost:8080/31aa70fc8589c52a763a2df36f304d28
Accept: text/plain

###
POST http://localhost:8080/
Content-Type: text/plain

https://learngitbranching.js.org/?locale=ru_RU

###
POST http://localhost:8080/api/shorten
Content-Type: application/json

{
    "url": "https://stackoverflow.com/questions/51774563/yaml-unmarshal-errors-cannot-unmarshal-string-into-time-duration-in-golang"
}

###
