// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.1
// 	protoc        v4.22.2
// source: proto/urlserver.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the URL ID
type GetURLByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UrlId string `protobuf:"bytes,1,opt,name=url_id,json=urlId,proto3" json:"url_id,omitempty"`
}

func (x *GetURLByIDRequest) Reset() {
	*x = GetURLByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_urlserver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetURLByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLByIDRequest) ProtoMessage() {}

func (x *GetURLByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_urlserver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLByIDRequest.ProtoReflect.Descriptor instead.
func (*GetURLByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_urlserver_proto_rawDescGZIP(), []int{0}
}

func (x *GetURLByIDRequest) GetUrlId() string {
	if x != nil {
		return x.UrlId
	}
	return ""
}

// The response message containing the URL
type GetURLByIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url   string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetURLByIDResponse) Reset() {
	*x = GetURLByIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_urlserver_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetURLByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLByIDResponse) ProtoMessage() {}

func (x *GetURLByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_urlserver_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLByIDResponse.ProtoReflect.Descriptor instead.
func (*GetURLByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_urlserver_proto_rawDescGZIP(), []int{1}
}

func (x *GetURLByIDResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GetURLByIDResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// The request message containing the user ID
type GetAllByUserIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetAllByUserIDRequest) Reset() {
	*x = GetAllByUserIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_urlserver_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllByUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllByUserIDRequest) ProtoMessage() {}

func (x *GetAllByUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_urlserver_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllByUserIDRequest.ProtoReflect.Descriptor instead.
func (*GetAllByUserIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_urlserver_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllByUserIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// The response message containing the list of URLs
type GetAllByUserIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FullUrls []*FullURL `protobuf:"bytes,1,rep,name=full_urls,json=fullUrls,proto3" json:"full_urls,omitempty"`
	Error    string     `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetAllByUserIDResponse) Reset() {
	*x = GetAllByUserIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_urlserver_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllByUserIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllByUserIDResponse) ProtoMessage() {}

func (x *GetAllByUserIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_urlserver_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllByUserIDResponse.ProtoReflect.Descriptor instead.
func (*GetAllByUserIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_urlserver_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllByUserIDResponse) GetFullUrls() []*FullURL {
	if x != nil {
		return x.FullUrls
	}
	return nil
}

func (x *GetAllByUserIDResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FullURL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortUrl    string `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	OriginalUrl string `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
}

func (x *FullURL) Reset() {
	*x = FullURL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_urlserver_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FullURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullURL) ProtoMessage() {}

func (x *FullURL) ProtoReflect() protoreflect.Message {
	mi := &file_proto_urlserver_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullURL.ProtoReflect.Descriptor instead.
func (*FullURL) Descriptor() ([]byte, []int) {
	return file_proto_urlserver_proto_rawDescGZIP(), []int{4}
}

func (x *FullURL) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *FullURL) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

// The request message containing the user ID and URL
type ReduceAndSaveURLRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Url    string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *ReduceAndSaveURLRequest) Reset() {
	*x = ReduceAndSaveURLRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_urlserver_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReduceAndSaveURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReduceAndSaveURLRequest) ProtoMessage() {}

func (x *ReduceAndSaveURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_urlserver_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReduceAndSaveURLRequest.ProtoReflect.Descriptor instead.
func (*ReduceAndSaveURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_urlserver_proto_rawDescGZIP(), []int{5}
}

func (x *ReduceAndSaveURLRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReduceAndSaveURLRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// The response message containing the shortened URL
type ReduceAndSaveURLResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortUrl string `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	Error    string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ReduceAndSaveURLResponse) Reset() {
	*x = ReduceAndSaveURLResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_urlserver_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReduceAndSaveURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReduceAndSaveURLResponse) ProtoMessage() {}

func (x *ReduceAndSaveURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_urlserver_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReduceAndSaveURLResponse.ProtoReflect.Descriptor instead.
func (*ReduceAndSaveURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_urlserver_proto_rawDescGZIP(), []int{6}
}

func (x *ReduceAndSaveURLResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *ReduceAndSaveURLResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ReduceURLToJSONRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     string      `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UrlRequest *URLRequest `protobuf:"bytes,2,opt,name=url_request,json=urlRequest,proto3" json:"url_request,omitempty"`
}

func (x *ReduceURLToJSONRequest) Reset() {
	*x = ReduceURLToJSONRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_urlserver_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReduceURLToJSONRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReduceURLToJSONRequest) ProtoMessage() {}

func (x *ReduceURLToJSONRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_urlserver_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReduceURLToJSONRequest.ProtoReflect.Descriptor instead.
func (*ReduceURLToJSONRequest) Descriptor() ([]byte, []int) {
	return file_proto_urlserver_proto_rawDescGZIP(), []int{7}
}

func (x *ReduceURLToJSONRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReduceURLToJSONRequest) GetUrlRequest() *URLRequest {
	if x != nil {
		return x.UrlRequest
	}
	return nil
}

// The response message containing the result
type ReduceURLToJSONResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UrlResponse *URLResponse `protobuf:"bytes,1,opt,name=url_response,json=urlResponse,proto3" json:"url_response,omitempty"`
	Error       string       `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ReduceURLToJSONResponse) Reset() {
	*x = ReduceURLToJSONResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_urlserver_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReduceURLToJSONResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReduceURLToJSONResponse) ProtoMessage() {}

func (x *ReduceURLToJSONResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_urlserver_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReduceURLToJSONResponse.ProtoReflect.Descriptor instead.
func (*ReduceURLToJSONResponse) Descriptor() ([]byte, []int) {
	return file_proto_urlserver_proto_rawDescGZIP(), []int{8}
}

func (x *ReduceURLToJSONResponse) GetUrlResponse() *URLResponse {
	if x != nil {
		return x.UrlResponse
	}
	return nil
}

func (x *ReduceURLToJSONResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type URLRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *URLRequest) Reset() {
	*x = URLRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_urlserver_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *URLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLRequest) ProtoMessage() {}

func (x *URLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_urlserver_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLRequest.ProtoReflect.Descriptor instead.
func (*URLRequest) Descriptor() ([]byte, []int) {
	return file_proto_urlserver_proto_rawDescGZIP(), []int{9}
}

func (x *URLRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type URLResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *URLResponse) Reset() {
	*x = URLResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_urlserver_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *URLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLResponse) ProtoMessage() {}

func (x *URLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_urlserver_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLResponse.ProtoReflect.Descriptor instead.
func (*URLResponse) Descriptor() ([]byte, []int) {
	return file_proto_urlserver_proto_rawDescGZIP(), []int{10}
}

func (x *URLResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

// The request message containing the user ID and list of URLs
type ReduceSeveralURLRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId            string              `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UrlWithIdRequests []*URLWithIDRequest `protobuf:"bytes,2,rep,name=url_with_id_requests,json=urlWithIdRequests,proto3" json:"url_with_id_requests,omitempty"`
}

func (x *ReduceSeveralURLRequest) Reset() {
	*x = ReduceSeveralURLRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_urlserver_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReduceSeveralURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReduceSeveralURLRequest) ProtoMessage() {}

func (x *ReduceSeveralURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_urlserver_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReduceSeveralURLRequest.ProtoReflect.Descriptor instead.
func (*ReduceSeveralURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_urlserver_proto_rawDescGZIP(), []int{11}
}

func (x *ReduceSeveralURLRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReduceSeveralURLRequest) GetUrlWithIdRequests() []*URLWithIDRequest {
	if x != nil {
		return x.UrlWithIdRequests
	}
	return nil
}

// The response message containing the list of URLs with IDs
type ReduceSeveralURLResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UrlWithIdResponses []*URLWithIDResponse `protobuf:"bytes,1,rep,name=url_with_id_responses,json=urlWithIdResponses,proto3" json:"url_with_id_responses,omitempty"`
	Error              string               `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ReduceSeveralURLResponse) Reset() {
	*x = ReduceSeveralURLResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_urlserver_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReduceSeveralURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReduceSeveralURLResponse) ProtoMessage() {}

func (x *ReduceSeveralURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_urlserver_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReduceSeveralURLResponse.ProtoReflect.Descriptor instead.
func (*ReduceSeveralURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_urlserver_proto_rawDescGZIP(), []int{12}
}

func (x *ReduceSeveralURLResponse) GetUrlWithIdResponses() []*URLWithIDResponse {
	if x != nil {
		return x.UrlWithIdResponses
	}
	return nil
}

func (x *ReduceSeveralURLResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type URLWithIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CorrelationId string `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	OriginalUrl   string `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
}

func (x *URLWithIDRequest) Reset() {
	*x = URLWithIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_urlserver_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *URLWithIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLWithIDRequest) ProtoMessage() {}

func (x *URLWithIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_urlserver_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLWithIDRequest.ProtoReflect.Descriptor instead.
func (*URLWithIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_urlserver_proto_rawDescGZIP(), []int{13}
}

func (x *URLWithIDRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *URLWithIDRequest) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type URLWithIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CorrelationId string `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	ShortUrl      string `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
}

func (x *URLWithIDResponse) Reset() {
	*x = URLWithIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_urlserver_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *URLWithIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLWithIDResponse) ProtoMessage() {}

func (x *URLWithIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_urlserver_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLWithIDResponse.ProtoReflect.Descriptor instead.
func (*URLWithIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_urlserver_proto_rawDescGZIP(), []int{14}
}

func (x *URLWithIDResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *URLWithIDResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type RemoveAllRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RemovingList []string `protobuf:"bytes,2,rep,name=removing_list,json=removingList,proto3" json:"removing_list,omitempty"`
}

func (x *RemoveAllRequest) Reset() {
	*x = RemoveAllRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_urlserver_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAllRequest) ProtoMessage() {}

func (x *RemoveAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_urlserver_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAllRequest.ProtoReflect.Descriptor instead.
func (*RemoveAllRequest) Descriptor() ([]byte, []int) {
	return file_proto_urlserver_proto_rawDescGZIP(), []int{15}
}

func (x *RemoveAllRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RemoveAllRequest) GetRemovingList() []string {
	if x != nil {
		return x.RemovingList
	}
	return nil
}

// The response message containing the error
type RemoveAllResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *RemoveAllResponse) Reset() {
	*x = RemoveAllResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_urlserver_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAllResponse) ProtoMessage() {}

func (x *RemoveAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_urlserver_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAllResponse.ProtoReflect.Descriptor instead.
func (*RemoveAllResponse) Descriptor() ([]byte, []int) {
	return file_proto_urlserver_proto_rawDescGZIP(), []int{16}
}

func (x *RemoveAllResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PingConnectionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingConnectionRequest) Reset() {
	*x = PingConnectionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_urlserver_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingConnectionRequest) ProtoMessage() {}

func (x *PingConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_urlserver_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingConnectionRequest.ProtoReflect.Descriptor instead.
func (*PingConnectionRequest) Descriptor() ([]byte, []int) {
	return file_proto_urlserver_proto_rawDescGZIP(), []int{17}
}

// The response message containing the error
type PingConnectionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *PingConnectionResponse) Reset() {
	*x = PingConnectionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_urlserver_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingConnectionResponse) ProtoMessage() {}

func (x *PingConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_urlserver_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingConnectionResponse.ProtoReflect.Descriptor instead.
func (*PingConnectionResponse) Descriptor() ([]byte, []int) {
	return file_proto_urlserver_proto_rawDescGZIP(), []int{18}
}

func (x *PingConnectionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetStatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_urlserver_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_urlserver_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_urlserver_proto_rawDescGZIP(), []int{19}
}

// The response message containing the stats
type GetStatsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stats *Stats `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_urlserver_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_urlserver_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_urlserver_proto_rawDescGZIP(), []int{20}
}

func (x *GetStatsResponse) GetStats() *Stats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *GetStatsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Stats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Urls  int64 `protobuf:"varint,1,opt,name=urls,proto3" json:"urls,omitempty"`
	Users int64 `protobuf:"varint,2,opt,name=users,proto3" json:"users,omitempty"`
}

func (x *Stats) Reset() {
	*x = Stats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_urlserver_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stats) ProtoMessage() {}

func (x *Stats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_urlserver_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stats.ProtoReflect.Descriptor instead.
func (*Stats) Descriptor() ([]byte, []int) {
	return file_proto_urlserver_proto_rawDescGZIP(), []int{21}
}

func (x *Stats) GetUrls() int64 {
	if x != nil {
		return x.Urls
	}
	return 0
}

func (x *Stats) GetUsers() int64 {
	if x != nil {
		return x.Users
	}
	return 0
}

var File_proto_urlserver_proto protoreflect.FileDescriptor

var file_proto_urlserver_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x72, 0x6c, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x64, 0x65, 0x6d, 0x6f, 0x22, 0x2a, 0x0a,
	0x11, 0x47, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x75, 0x72, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x75, 0x72, 0x6c, 0x49, 0x64, 0x22, 0x3c, 0x0a, 0x12, 0x47, 0x65, 0x74,
	0x55, 0x52, 0x4c, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72,
	0x6c, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x30, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x5a, 0x0a, 0x16, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x09, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x75, 0x72, 0x6c, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x46, 0x75,
	0x6c, 0x6c, 0x55, 0x52, 0x4c, 0x52, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x55, 0x72, 0x6c, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x49, 0x0a, 0x07, 0x46, 0x75, 0x6c, 0x6c, 0x55, 0x52, 0x4c,
	0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x12, 0x21, 0x0a,
	0x0c, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x55, 0x72, 0x6c,
	0x22, 0x44, 0x0a, 0x17, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x41, 0x6e, 0x64, 0x53, 0x61, 0x76,
	0x65, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x4d, 0x0a, 0x18, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65,
	0x41, 0x6e, 0x64, 0x53, 0x61, 0x76, 0x65, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x64, 0x0a, 0x16, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x55,
	0x52, 0x4c, 0x54, 0x6f, 0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x31, 0x0a, 0x0b, 0x75, 0x72, 0x6c, 0x5f,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52,
	0x0a, 0x75, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x65, 0x0a, 0x17, 0x52,
	0x65, 0x64, 0x75, 0x63, 0x65, 0x55, 0x52, 0x4c, 0x54, 0x6f, 0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x0c, 0x75, 0x72, 0x6c, 0x5f, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x64,
	0x65, 0x6d, 0x6f, 0x2e, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52,
	0x0b, 0x75, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x22, 0x1e, 0x0a, 0x0a, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x72, 0x6c, 0x22, 0x25, 0x0a, 0x0b, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x7b, 0x0a, 0x17, 0x52, 0x65, 0x64,
	0x75, 0x63, 0x65, 0x53, 0x65, 0x76, 0x65, 0x72, 0x61, 0x6c, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x47, 0x0a,
	0x14, 0x75, 0x72, 0x6c, 0x5f, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x69, 0x64, 0x5f, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x64, 0x65,
	0x6d, 0x6f, 0x2e, 0x55, 0x52, 0x4c, 0x57, 0x69, 0x74, 0x68, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x52, 0x11, 0x75, 0x72, 0x6c, 0x57, 0x69, 0x74, 0x68, 0x49, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x22, 0x7c, 0x0a, 0x18, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65,
	0x53, 0x65, 0x76, 0x65, 0x72, 0x61, 0x6c, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x4a, 0x0a, 0x15, 0x75, 0x72, 0x6c, 0x5f, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x69,
	0x64, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x55, 0x52, 0x4c, 0x57, 0x69, 0x74, 0x68,
	0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x12, 0x75, 0x72, 0x6c, 0x57,
	0x69, 0x74, 0x68, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x22, 0x5c, 0x0a, 0x10, 0x55, 0x52, 0x4c, 0x57, 0x69, 0x74, 0x68, 0x49,
	0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x72, 0x72,
	0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12,
	0x21, 0x0a, 0x0c, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x75, 0x72, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x55,
	0x72, 0x6c, 0x22, 0x57, 0x0a, 0x11, 0x55, 0x52, 0x4c, 0x57, 0x69, 0x74, 0x68, 0x49, 0x44, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x72, 0x72, 0x65,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x22, 0x50, 0x0a, 0x10, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x6d, 0x6f,
	0x76, 0x69, 0x6e, 0x67, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0c, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x29, 0x0a,
	0x11, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x17, 0x0a, 0x15, 0x50, 0x69, 0x6e, 0x67,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x2e, 0x0a, 0x16, 0x50, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x22, 0x11, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x4b, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x73, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x22, 0x31, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x72,
	0x6c, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x75,
	0x73, 0x65, 0x72, 0x73, 0x32, 0xd2, 0x04, 0x0a, 0x04, 0x55, 0x52, 0x4c, 0x73, 0x12, 0x3f, 0x0a,
	0x0a, 0x47, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x42, 0x79, 0x49, 0x44, 0x12, 0x17, 0x2e, 0x64, 0x65,
	0x6d, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x55,
	0x52, 0x4c, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b,
	0x0a, 0x0e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x12, 0x1b, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x79,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e,
	0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x79, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x51, 0x0a, 0x10, 0x52,
	0x65, 0x64, 0x75, 0x63, 0x65, 0x41, 0x6e, 0x64, 0x53, 0x61, 0x76, 0x65, 0x55, 0x52, 0x4c, 0x12,
	0x1d, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x41, 0x6e, 0x64,
	0x53, 0x61, 0x76, 0x65, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e,
	0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x41, 0x6e, 0x64, 0x53,
	0x61, 0x76, 0x65, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e,
	0x0a, 0x0f, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x55, 0x52, 0x4c, 0x54, 0x6f, 0x4a, 0x53, 0x4f,
	0x4e, 0x12, 0x1c, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x55,
	0x52, 0x4c, 0x54, 0x6f, 0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1d, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x55, 0x52, 0x4c,
	0x54, 0x6f, 0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x51,
	0x0a, 0x10, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x53, 0x65, 0x76, 0x65, 0x72, 0x61, 0x6c, 0x55,
	0x52, 0x4c, 0x12, 0x1d, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65,
	0x53, 0x65, 0x76, 0x65, 0x72, 0x61, 0x6c, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1e, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x53,
	0x65, 0x76, 0x65, 0x72, 0x61, 0x6c, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3c, 0x0a, 0x09, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x41, 0x6c, 0x6c, 0x12, 0x16,
	0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x41, 0x6c, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x4b, 0x0a, 0x0e, 0x50, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1b, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c,
	0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x08,
	0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x15, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e,
	0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x16, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x23, 0x5a, 0x21, 0x70, 0x72, 0x61,
	0x63, 0x74, 0x69, 0x63, 0x75, 0x6d, 0x2d, 0x75, 0x72, 0x6c, 0x2d, 0x72, 0x65, 0x64, 0x75, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_urlserver_proto_rawDescOnce sync.Once
	file_proto_urlserver_proto_rawDescData = file_proto_urlserver_proto_rawDesc
)

func file_proto_urlserver_proto_rawDescGZIP() []byte {
	file_proto_urlserver_proto_rawDescOnce.Do(func() {
		file_proto_urlserver_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_urlserver_proto_rawDescData)
	})
	return file_proto_urlserver_proto_rawDescData
}

var file_proto_urlserver_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_proto_urlserver_proto_goTypes = []interface{}{
	(*GetURLByIDRequest)(nil),        // 0: demo.GetURLByIDRequest
	(*GetURLByIDResponse)(nil),       // 1: demo.GetURLByIDResponse
	(*GetAllByUserIDRequest)(nil),    // 2: demo.GetAllByUserIDRequest
	(*GetAllByUserIDResponse)(nil),   // 3: demo.GetAllByUserIDResponse
	(*FullURL)(nil),                  // 4: demo.FullURL
	(*ReduceAndSaveURLRequest)(nil),  // 5: demo.ReduceAndSaveURLRequest
	(*ReduceAndSaveURLResponse)(nil), // 6: demo.ReduceAndSaveURLResponse
	(*ReduceURLToJSONRequest)(nil),   // 7: demo.ReduceURLToJSONRequest
	(*ReduceURLToJSONResponse)(nil),  // 8: demo.ReduceURLToJSONResponse
	(*URLRequest)(nil),               // 9: demo.URLRequest
	(*URLResponse)(nil),              // 10: demo.URLResponse
	(*ReduceSeveralURLRequest)(nil),  // 11: demo.ReduceSeveralURLRequest
	(*ReduceSeveralURLResponse)(nil), // 12: demo.ReduceSeveralURLResponse
	(*URLWithIDRequest)(nil),         // 13: demo.URLWithIDRequest
	(*URLWithIDResponse)(nil),        // 14: demo.URLWithIDResponse
	(*RemoveAllRequest)(nil),         // 15: demo.RemoveAllRequest
	(*RemoveAllResponse)(nil),        // 16: demo.RemoveAllResponse
	(*PingConnectionRequest)(nil),    // 17: demo.PingConnectionRequest
	(*PingConnectionResponse)(nil),   // 18: demo.PingConnectionResponse
	(*GetStatsRequest)(nil),          // 19: demo.GetStatsRequest
	(*GetStatsResponse)(nil),         // 20: demo.GetStatsResponse
	(*Stats)(nil),                    // 21: demo.Stats
}
var file_proto_urlserver_proto_depIdxs = []int32{
	4,  // 0: demo.GetAllByUserIDResponse.full_urls:type_name -> demo.FullURL
	9,  // 1: demo.ReduceURLToJSONRequest.url_request:type_name -> demo.URLRequest
	10, // 2: demo.ReduceURLToJSONResponse.url_response:type_name -> demo.URLResponse
	13, // 3: demo.ReduceSeveralURLRequest.url_with_id_requests:type_name -> demo.URLWithIDRequest
	14, // 4: demo.ReduceSeveralURLResponse.url_with_id_responses:type_name -> demo.URLWithIDResponse
	21, // 5: demo.GetStatsResponse.stats:type_name -> demo.Stats
	0,  // 6: demo.URLs.GetURLByID:input_type -> demo.GetURLByIDRequest
	2,  // 7: demo.URLs.GetAllByUserID:input_type -> demo.GetAllByUserIDRequest
	5,  // 8: demo.URLs.ReduceAndSaveURL:input_type -> demo.ReduceAndSaveURLRequest
	7,  // 9: demo.URLs.ReduceURLToJSON:input_type -> demo.ReduceURLToJSONRequest
	11, // 10: demo.URLs.ReduceSeveralURL:input_type -> demo.ReduceSeveralURLRequest
	15, // 11: demo.URLs.RemoveAll:input_type -> demo.RemoveAllRequest
	17, // 12: demo.URLs.PingConnection:input_type -> demo.PingConnectionRequest
	19, // 13: demo.URLs.GetStats:input_type -> demo.GetStatsRequest
	1,  // 14: demo.URLs.GetURLByID:output_type -> demo.GetURLByIDResponse
	3,  // 15: demo.URLs.GetAllByUserID:output_type -> demo.GetAllByUserIDResponse
	6,  // 16: demo.URLs.ReduceAndSaveURL:output_type -> demo.ReduceAndSaveURLResponse
	8,  // 17: demo.URLs.ReduceURLToJSON:output_type -> demo.ReduceURLToJSONResponse
	12, // 18: demo.URLs.ReduceSeveralURL:output_type -> demo.ReduceSeveralURLResponse
	16, // 19: demo.URLs.RemoveAll:output_type -> demo.RemoveAllResponse
	18, // 20: demo.URLs.PingConnection:output_type -> demo.PingConnectionResponse
	20, // 21: demo.URLs.GetStats:output_type -> demo.GetStatsResponse
	14, // [14:22] is the sub-list for method output_type
	6,  // [6:14] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_urlserver_proto_init() }
func file_proto_urlserver_proto_init() {
	if File_proto_urlserver_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_urlserver_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetURLByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_urlserver_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetURLByIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_urlserver_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllByUserIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_urlserver_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllByUserIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_urlserver_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FullURL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_urlserver_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReduceAndSaveURLRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_urlserver_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReduceAndSaveURLResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_urlserver_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReduceURLToJSONRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_urlserver_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReduceURLToJSONResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_urlserver_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*URLRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_urlserver_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*URLResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_urlserver_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReduceSeveralURLRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_urlserver_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReduceSeveralURLResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_urlserver_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*URLWithIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_urlserver_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*URLWithIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_urlserver_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveAllRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_urlserver_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveAllResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_urlserver_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingConnectionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_urlserver_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingConnectionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_urlserver_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStatsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_urlserver_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStatsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_urlserver_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_urlserver_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_urlserver_proto_goTypes,
		DependencyIndexes: file_proto_urlserver_proto_depIdxs,
		MessageInfos:      file_proto_urlserver_proto_msgTypes,
	}.Build()
	File_proto_urlserver_proto = out.File
	file_proto_urlserver_proto_rawDesc = nil
	file_proto_urlserver_proto_goTypes = nil
	file_proto_urlserver_proto_depIdxs = nil
}
